server:
  port: 8081
  description: 获取Token，API权限等

spring:
  application:
    name: peach-auth-service
    module-code: AUTH
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

peach:
  jwt:
    expires-in: ${PEACH_JWT_EXPIRES_IN:3600}
    refresh-expires-in: ${PEACH_JWT_REFRESH_EXPIRES_IN:604800}
