server:
  port: 8081
  description: 获取Token，API权限等

spring:
  application:
    name: peach-auth-service
    module-code: AUTH
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:192.168.99.100:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
